-- ==========================================
-- SnapGuard AIGC (智御·瞬息) Supabase 初始化脚本
-- ==========================================

-- 1. 创建 profiles 表，与 Supabase 内置的 auth.users 联动绑定
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY, -- 对应原 users 表，并绑定内置用户
  username TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'user',
  display_name TEXT,
  plan TEXT DEFAULT 'free',
  -- 兼容旧字段（逐步迁移）
  quota_used INTEGER DEFAULT 0,
  quota_total INTEGER DEFAULT 10,
  -- 新额度体系：分别限制嵌入和检测
  quota_embed_used INTEGER DEFAULT 0,
  quota_embed_total INTEGER DEFAULT 50,    -- 免费版默认50次嵌入
  quota_detect_used INTEGER DEFAULT 0,
  quota_detect_total INTEGER DEFAULT 20,   -- 免费版默认20次检测
  -- 订阅周期体系
  subscription_period TEXT DEFAULT NULL,  -- 'month' 月付 / 'year' 年付
  subscription_expires_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,  -- 订阅到期时间
  subscription_status TEXT DEFAULT 'inactive',  -- 'active'/'expired'/'cancelled'/'inactive'
  subscription_started_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,  -- 订阅开始时间
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. 创建 authors 表 (版权所有者信息)
CREATE TABLE public.authors (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE UNIQUE NOT NULL,
  author_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. 创建 watermarked_assets 表 (数字指纹资产)
CREATE TABLE public.watermarked_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  filename TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  phash TEXT,
  output_path TEXT,
  input_path TEXT,
  timestamp TEXT NOT NULL,
  psnr REAL,
  tx_hash TEXT DEFAULT NULL,
  block_height INTEGER DEFAULT NULL,
  asset_type TEXT DEFAULT 'image',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. 创建 infringement_records 表 (侵权监测记录)
CREATE TABLE public.infringement_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id BIGINT REFERENCES public.watermarked_assets(id) ON DELETE CASCADE,
  source_url TEXT,
  similarity REAL,
  matched_user_id UUID,
  detected_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ==========================================
-- 💡 以下开启 Supabase RLS (行级安全策略) 保护数据安全
-- ==========================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.authors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.watermarked_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.infringement_records ENABLE ROW LEVEL SECURITY;

-- 只有自己可以读取和更新自己的 profiles
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING ( auth.uid() = id );
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING ( auth.uid() = id );

-- Assets的策略: 只能查看自己的作品
CREATE POLICY "Users can view own assets" ON public.watermarked_assets FOR SELECT USING ( auth.uid() = user_id );

-- 侵权记录的策略: 只能查看属于自己资产的侵权
CREATE POLICY "Users can view own infringement records" ON public.infringement_records 
FOR SELECT USING ( 
  asset_id IN (SELECT id FROM public.watermarked_assets WHERE user_id = auth.uid()) 
);

-- ==========================================
-- 🔔 开启 Realtime 实时订阅 (重要：为了让前端瞬间收到报警)
-- ==========================================
-- 配置 publication 以支持 Realtime
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table public.infringement_records;
alter publication supabase_realtime add table public.watermarked_assets;

-- ==========================================
-- 🚀 触发器: 当用户注册时，自动生成 profile 和 author 记录
-- ==========================================
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, display_name)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'display_name');

  INSERT INTO public.authors (user_id, author_name)
  VALUES (new.id, new.raw_user_meta_data->>'display_name');
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

UPDATE public.profiles
SET 
  role = 'admin',
  plan = 'enterprise',
  quota_total = 9999999,
  display_name = 'ZSY Pioneer'
WHERE username = 'zsypioneer@snapguard.com';

